<programa>         ::= "apresentar" <bloco> "encerrar"
<bloco>            ::= "{" <lista_comandos> "}"
<lista_comandos>   ::= { <comando> }
<comando>          ::= <declaracao> | <atribuicao> | <condicional> | <loop> | <saida> | <bloco_ato>
<declaracao>       ::= "personagem" <identificador> [ "=" <expressao> ] ";"
<atribuicao>       ::= <identificador> "=" <expressao> ";"
<condicional>      ::= "se" "(" <expressao> ")" <bloco_ato> [ "senao" <bloco_ato> ]
<loop>             ::= "repetir" "(" <expressao> ")" <bloco_ato> | "caminhar" "(" <atribuicao> <expressao> ";" <atribuicao> ")" <bloco_ato>
<saida>            ::= "fala" "(" <expressao> ")" ";"
<bloco_ato>        ::= "{" <lista_comandos> "}"
<expressao>        ::= <termo> { ("+" | "-") <termo> }
<termo>            ::= <fator> { ("*" | "/" ) <fator> }
<fator>            ::= <numero> | <identificador> | "(" <expressao> ")"
<numero>           ::= [ "-" ] <digito> { <digito> }
<digito>           ::= "0".."9"
<identificador>    ::= <letra> { <letra> | <digito> | "_" }
<letra>            ::= "a".."z"
