#ifndef TOKENS_H
#define TOKENS_H

typedef enum {
    TOKEN_EOF = 0,
    TOKEN_IDENTIFIER,
    TOKEN_NUMBER,
    TOKEN_STRING,
    
    TOKEN_BOOT,
    TOKEN_SHUTDOWN,
    TOKEN_BYTE,
    TOKEN_BIT,
    TOKEN_CHIP,
    TOKEN_SCAN_BEGIN,
    TOKEN_SCAN_END,
    TOKEN_PING,
    TOKEN_PROCESS,
    TOKEN_PING_END,
    TOKEN_PONG,
    TOKEN_PONG_END,
    TOKEN_LOOP,
    TOKEN_AS,
    TOKEN_LOOP_END,
    TOKEN_STREAM,
    TOKEN_STREAM_END,
    TOKEN_MODULE,
    TOKEN_MODULE_END,
    TOKEN_RETURN,
    TOKEN_LOG,
    
    TOKEN_PLUS,
    TOKEN_MINUS,
    TOKEN_MULTIPLY,
    TOKEN_DIVIDE,
    TOKEN_EQUAL,
    TOKEN_NOT_EQUAL,
    TOKEN_GREATER,
    TOKEN_LESS,
    TOKEN_GREATER_EQUAL,
    TOKEN_LESS_EQUAL,
    TOKEN_AND,
    TOKEN_OR,
    TOKEN_ASSIGN,
    
    TOKEN_LPAREN,
    TOKEN_RPAREN,
    TOKEN_LBRACKET,
    TOKEN_RBRACKET,
    TOKEN_COMMA
} TokenType;

#endif